### ISSUE TITLE
https://jwt.io/ não valida

### ISSUE THREAD

**Issue by oilujrasec** [natanbueno/fp-jsonwebtoken#2]
Ainda não entendo muito bem de token,

mais token gerado nesse exemplos, não valida no https://jwt.io/

O que acontece e porque?

**Comment by natanbueno** [comment]
Quando vc colar o token no site do jwt.io, você precisa no lado direito nos campos Verify Signature digitar sua ou qualquer outra chave key e ai o token irá ser validado. exemplo:
HMACSHA256(
  base64UrlEncode(header) + "." +
  base64UrlEncode(payload),
  bob-esponja <---- Digita aqui sua chave key
)
Minha sugestão também é ver um issues aqui que foi fechado já respondendo essa mesma pergunta.
